services:
  db:
    image: postgres:16
    container_name: askdb-db
    environment:
      POSTGRES_USER: askdb
      POSTGRES_PASSWORD: askdb
      POSTGRES_DB: askdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data/sample_saas_dump.sql:/docker-entrypoint-initdb.d/01_seed.sql:ro

  redis:
    image: redis:7
    container_name: askdb-redis
    ports:
      - "6379:6379"

volumes:
  db_data:
