services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: askdb
      POSTGRES_PASSWORD: askdb
      POSTGRES_DB: askdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data/sample_saas_dump.sql:/docker-entrypoint-initdb.d/01_seed.sql:ro
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: ./apps/api
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./apps/api:/app
      - ./apps/api/tests/snapshots:/app/tests/snapshots  # 👈 ONLY mount snapshots dir, no `:ro`
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://askdb:askdb@db:5432/askdb
      - REDIS_URL=redis://redis:6379
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}  # 👈 Add Clerk env
      - CLERK_DEV_BYPASS=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
      - redis     # 👈 Also wait for redis to start
    ports:
      - "8001:8000"

  slackbot:
    build: ./apps/slackbot
    command: uvicorn main:api --host 0.0.0.0 --port 8000 --reload
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - ASKDB_API_URL=http://api:8000/ask
    depends_on:
      - api
    ports:
      - "8000:8000"


volumes:
  db_data:
